CREATE TABLE IF NOT EXISTS `apcstend` (
    `Id` INT NOT NULL AUTO_INCREMENT, 
    `LocationCode` Varchar(30) NULL, 
    `CancelledTimeStamp` DateTime NULL, 
    `Key` INT NOT NULL, 
    `Tran` INT NULL, 
    `Date` DateTime NULL, 
    `Code` Varchar(2) NULL, 
    `Status` Varchar(1) NULL, 
    `Amount` Float NULL, 
    `ccnum` Varchar(25) NULL, 
    `ccexp` Varchar(5) NULL, 
    `ccaprval` Varchar(25) NULL, 
    `glnum` Varchar(255) NULL, 
    `Ztill` Varchar(10) NULL, 
    `Znum` INT NULL, 
    `User` Varchar(10) NULL, 
    `CCTransactionID` Varchar(50) NULL, 
    `CardHolder` Varchar(50) NULL, 
    `CCMessage` Varchar(50) NULL, 
    `SignatureStatus` Varchar(20) NULL, 
    `Manager` Varchar(20) NULL, 
    `ResponseData` Text NULL, 
    `Created` Text NULL, 
    `MasterId` INT NULL, 
    `Origin` Varchar(20) NULL, 
    `Description` Varchar(25) NULL, 
    PRIMARY KEY ( `Id` )
);